host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: ubi8
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

managers:
  # add this to managers if we want to add python deps
  # - name: pipfile-requirements
  - name: update
    configuration:
      labels: [bot]
  - name: info
  - name: version
    configuration:
      maintainers:
        - ChristianMeyndt
        - idemir-ids
        - erikerlandson
        - harshad16
        - mightynerderic
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
